---
version: "2.1"
services:
  calibre-web:
    build: build-web/
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /home/ubuntu/calibre/data:/config
      - /home/ubuntu/calibre/library:/books
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
  calibre:
    build: build-calibre/
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - PASSWORD=something
    volumes:
      - /home/ubuntu/calibre/data:/config
      - /home/ubuntu/calibre/library:/books
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped