version: "3.8"

services:
  web:
    build: .
    environment:
        - 'PUID=1000'
        - 'PGID=1000'
        - 'TZ=Australia/Melbourne'
        - 'DOCKER_MODS=linuxserver/calibre-web:calibrexq'
    expose:
        - 80
    volumes:
        - /home/ubuntu/calibre/data:/config
        - /home/ubuntu/calibre/books:/books
    restart: unless-stopped
