version: "3.8"

services:
  web:
    image: linuxserver/calibre-web
    environment:
        - 'PUID=1000'
        - 'PGID=1000'
        - 'TZ=Australia/Melbourne'
        - 'DOCKER_MODS=linuxserver/calibre-web:calibrexq'
    expose:
        - 80
    volumes:
        - /config:/home/ubuntu/calibre/data
        - /books:/home/ubuntu/calibre/books
    restart: unless-stopped
